### ISSUE TITLE
empty selection in character select

### ISSUE THREAD

**Issue by TK3600** [Ariescyn/EldenRing-Save-Manager#12]
did not have this problem in 1.4.2

when select save > character, all fields are empty

**Comment by Ariescyn** [comment]
Can you elaborate on the issue? Do you mean when you go to character manager and click select, none of your characters appear? Does it happen with a different save file? (like one on the nexus)

**Comment by TK3600** [comment]
yes. I use the same file on previous version and the character appears

**Comment by TK3600** [comment]
I just tested it 1.4.3 works too.

**Comment by TK3600** [comment]
Lastly it would be nice to make the steam name patcher optional. I have a pirated copy and a legit copy. It keeps changing to the pirated version.

**Comment by TK3600** [comment]
I just tested again. It appears the issues begin at version 1.4.4.

**Comment by Ariescyn** [comment]
You can manually change the Steam ID of a save but ill make it optional on a future update. Where is the save file location for your pirated copy and do you use a separate copy of the save manager for each copy of the game?

Thanks for the information, its odd that i cannot replicate this issue on my own. Could you email me your save file to scyntacks94@gmail.com?

**Comment by TK3600** [comment]
done.

**Comment by TK3600** [comment]
Nevermind, I found out by deleting the save then loading it again it is no longer bugged in 1.4.6. Sorry!
