### ISSUE TITLE
Source for 1.46 tarball is 1.45

### ISSUE THREAD

**Issue by promisedlandt** [Ariescyn/EldenRing-Save-Manager#13]
The source at https://github.com/Ariescyn/EldenRing-Save-Manager/archive/refs/tags/v1.46.tar.gz should be 1.46, but is actually 1.45.

![image](https://user-images.githubusercontent.com/557201/167408341-8c85a2fc-7f08-418b-ba02-3b7bae5ae2a4.png)

**Comment by Ariescyn** [comment]
Sorry, on the next release ill make sure it's correct.
