### ISSUE TITLE
There needs to be an option to change the default steamID

### ISSUE THREAD

**Issue by ORLOX93** [Ariescyn/EldenRing-Save-Manager#15]
My 2 brothers play ER on the same pc as me. I know my own steamID, but when i import the save, the program keeps telling me that the steamID of the file doesnt match my own steamID (which does indeed match), so it changes it to my brother's steamID.

If i ever press the load save button, i will delete his savefile. I need to change the default steamID in the program so this doesnt happen.

**Comment by Ariescyn** [comment]
I have a quick question, does the EldenRing game save directory have folders with each steam id?

for example:
GraphicsConfig.xml
72894282482482        < your id
39432423423423        < brothers id

**Comment by ORLOX93** [comment]
Hey, sorry for the late response, i got no notifications from github. And yeah that's how it works, you get a random id, and your saves go on a folder with that name.

**Comment by Ariescyn** [comment]
Is this an issue for you still?
I changed up how steamids are handled in newer versions so shouldn't be an issue as long as you have a copy of the save manager for each user
