### ISSUE TITLE
cant add more rune items to my inventory 

### ISSUE THREAD

**Issue by madKnill** [Ariescyn/EldenRing-Save-Manager#17]
After going through the process of grabbing a lords rune item, i'd tried to add more into the inventory, but it just keeps saying to make sure i have at least one of the item in my inventory, even though I do 
![example2](https://user-images.githubusercontent.com/81501021/168508446-e072fd8c-5208-4f51-a486-05b893dfd349.png)
![example1](https://user-images.githubusercontent.com/81501021/168508449-81c5db59-da5d-4c55-8a98-ce0b2de5494a.png)

**Comment by madKnill** [comment]
after some more use of the tool and thinking about it slowly i figured out the problem. I hadn't saved the instance of my character when it had the lords rune in it, but the character when I first used the tool instead. So sorry if this worried you! Thanks for making this awesome tool!

**Comment by Ariescyn** [comment]
Did you resolve this issue?

**Comment by madKnill** [comment]
> Did you resolve this issue?

yes I apologize for closing and reopening this, I decided to rest on it and figured it out after I woke up. Sorry to worry you, thanks for making this awesome tool!
