### ISSUE TITLE
Stat Changes Fail to Apply

### ISSUE THREAD

**Issue by KitFoxy** [Ariescyn/EldenRing-Save-Manager#18]
**Action Taken**
Open stat menu, make changes, try to save. Check values in game.

**Expected Behaviour**
Changes in save file.

**Actual Behaviour**
 Fails to change stats.

**Steps to Reproduce**
1. Find save.
2. Get stats via button in stat editor menu. 
3. Adjust values and click set.
4. Check values in game.

**Other Information**

- Has been attempted with game open.
- Has been attempted with game closed.
- Has been attempted closing game after making changes outside of game.
- On a Linux system.

**Comment by Ariescyn** [comment]
Stupid question bu after making changes to the save file, are you clicking "Load Save"?

**Comment by KitFoxy** [comment]
Didn't note that under documentation. My bad. Sorry for the delay, got struck with the plague.
