### ISSUE TITLE
Feature Request: face slider transfer

### ISSUE THREAD

**Issue by chozandrias76** [Ariescyn/EldenRing-Save-Manager#19]
As a user
I would like to retain copies of my character's face sliders
So that I can back them up, and transfer them into existing saves
Without needing the original save with the rest of its baggage

**Comment by chozandrias76** [comment]
I could attempt to develop this feature, but I am just getting my feet wet in your code and am not proficient.

**Comment by Ariescyn** [comment]
If you want to just do the save file analysis, I can do the rest. I'm not really planning on adding many more features as I wanna start working on another project. A boss arcade mod where you can pick a boss to fight, then choose a character presets or custom build. 

As far as analyzing the save, I can offer help if you needed it
