### ISSUE TITLE
Add instructions for building portable executable from source

### ISSUE THREAD

**Issue by jasper1378** [Ariescyn/EldenRing-Save-Manager#21]
Hello, 

I was hoping you could add instructions on how to build the portable windows executable (such as in the official releases). I apologize if this is a stupid questions, I'm not very familiar with Python.

Thanks,
Jasper

**Comment by Ariescyn** [comment]
just use pip to install pyinstaller, then go to the README.MD and follow the instructions for installing dependencies, then finally run the pyinstaller command in the README.MD

**Comment by Ariescyn** [comment]
I should add that after running th pyinstaller command, it will generate a folder called dist with the executable inside. Move that exe into the same directory as the data folder (not in the data folder)

**Comment by jasper1378** [comment]
Cool, thank you so much!
