### ISSUE TITLE
Replace item tool not replacing

### ISSUE THREAD

**Issue by gaardiolor** [Ariescyn/EldenRing-Save-Manager#29]
Hello,

I've added the Magic Scorpion Charm as a custom item [208, 7]

Just tried to replace a "Somber Smithing Stone [1]" (had one in my inventory) with the Magic Scorpion Charm, didn't work. The Somber Smithing Stone [1] disappeared.. but the Charm is nowhere to be found. Do the items need to be from the same category ?

I did notice the "Adding weapons and other unstackable items are currently not supported." in https://github.com/Ariescyn/EldenRing-Save-Manager/blob/main/ALL_ITEM_IDS.md , is replacement also not supported ?

Thanks!

**Comment by Ariescyn** [comment]
While on the item replace window, if you click Help > Readme it says:

This feature is experimental and may not work for everything!
-Weapons/Armor is unsupported
-You should try to replace an item with another of the same category ex: crafting materials
-Try not to replace an item you already have, or you will get two stacks of the same item
-Not all items will appear in the inventory box, only detected items that can be overwritten
-You must have Tarnished's Wizened Finger in your inventory (First item you pickup)

Also I should add that not all item ID's on the master spreadsheet are tested.
Crafting materials, smithing stones, runes, etc should all work.

Also, i was able to replace crafting materials with some items like larval tears, so overwriting an item from a different category is possible but should be avoided if possible.

**Comment by gaardiolor** [comment]
Ah yes. I have the finger in my inventory. I have tried to replace one talisman with another, the Flamedrake Talisman +1 with Magic Scorpion Charm, but that didn't work. With Weapons/Armor I suppose you also mean talismans right ? Would be nice if that can be supported in the future :)

**Comment by Ariescyn** [comment]
Yes sorry the item must be stackable. I will make that more clear on the next update. 
Non stackables like armor are handled a lot differently in the save file. To be honest im tired of staring at numbers trying to figure out what is going on lol.
