### ISSUE TITLE
Request: Add support for Seamless co-op game files

### ISSUE THREAD

**Issue by Muramas** [Ariescyn/EldenRing-Save-Manager#30]
Would it be possible to support saves from the seamless co-op version? The saves are renamed to .co2 to separate them from the normal game.

https://github.com/LukeYui/EldenRingSeamlessCoopRelease

**Comment by Ariescyn** [comment]
Yeah go to File > Seamless co-op mode and click enable!

This toggles the manager to only work with .co2 file extensions. It's recommended to have two copies of the save manager, one for seamless and one for vanilla to avoid confusion.
