### ISSUE TITLE
Character Renaming Name is part of another name

### ISSUE THREAD

**Issue by ixidion** [Ariescyn/EldenRing-Save-Manager#31]
I have a savefile with names, e.g.
```
abc
abcd
xyz abc
```

When I rename Slot1 "abc" with "cba", the result is the following
```
cba
cbad
xyz cba
```

The other slot names are changed as well. Is it possible to do an exact matching, otherwise only workarounds will help.

**Comment by Ariescyn** [comment]
Unfortunately the program replaces ALL occurrences of a name. I might rewrite it in the future but I'm busy with other projects right now

**Comment by Ariescyn** [comment]
Fixed in v1.66

**Comment by ixidion** [comment]
Works, thank you.
