### ISSUE TITLE
Pyinstaller command does not work on linux

### ISSUE THREAD

**Issue by JakeDevs** [Ariescyn/EldenRing-Save-Manager#32]
pyinstaller --onefile --windowed --icon=.\data\icon.ico .\SaveManager.py .\hexedit.py .\stat_progression.py .\itemdata.py .\os_layer.py

This command does not work because the slashes are backslashes which don't work in linux.
The correct command is as follows: 

pyinstaller --onefile --windowed --icon=./data/icon.ico ./SaveManager.py ./hexedit.py ./stat_progression.py ./itemdata.py ./os_layer.py

please update the readme

**Comment by Ariescyn** [comment]
I also forgot to add ./allitems_dict.py, fixed now

**Comment by JakeDevs** [comment]
thanks, great work on this project
