### ISSUE TITLE
Items list

### ISSUE THREAD

**Issue by bpfoldesi** [Ariescyn/EldenRing-Save-Manager#38]
I can’t find the full list of items is it a separate download?

**Comment by Ariescyn** [comment]
https://github.com/Ariescyn/EldenRing-Save-Manager/blob/main/ALL_ITEM_IDS.md

**Comment by bpfoldesi** [comment]
I downloaded the latest version and can’t find the ID search. How dio I get to it?

**Comment by Ariescyn** [comment]
Sorry for the late reply. You can find the Search tool in:   Tools > Inventory editor > Actions > Search
