### ISSUE TITLE
Small crashing issue

### ISSUE THREAD

**Issue by JaimePSantos** [Ariescyn/EldenRing-Save-Manager#4]
Hello,

The program seems to crash after opening the help section of the character management tool:

![image](https://user-images.githubusercontent.com/50669048/162040981-78b83844-bcbb-4a59-b436-ebdcdb200a90.png)

I installed the program through the release files a few days ago and used the updater to get today's release.
I seem to be able to reproduce this behavior, but I'm not sure if it is a problem with my installation.
Its not a big deal, but I figured you'd want to know about it!

Thanks!

**Comment by Ariescyn** [comment]
Thanks i appreciate you letting me know!

Did you leave notepad open? if you try to interact with the program and the
readme is still open in notepad, the app wont respond until you close
notepad. Ill try to fix this on the next update
Also right after i submitted the code to microsoft defender, i noticed an
issue where a random rename pop-up appears after clicking watch video. It
doesnt break the app but ill remove that as well

**Comment by Ariescyn** [comment]
This is fixed in v1.41
