### ISSUE TITLE
Feature Request/Issue Non-steam wine game

### ISSUE THREAD

**Issue by poboy975** [Ariescyn/EldenRing-Save-Manager#40]
Hello, I'm running Elden Ring through wine, not steam. How can I edit the save file? I can import the save just fine, but it won't let me save the file. When I try it tells me to set the default game dir, but, the game dir is looking for the steam id, which I don't have since it's a non steam game.

**Comment by Ariescyn** [comment]
Hey there, i can remove that constraint in a future update but in the meantime you can open the ./data/config.json and manually enter your file path

**Comment by poboy975** [comment]
Perfect! Thank you!
