### ISSUE TITLE
Feature Request: On clicking "Load Save", prompt to save current game file to avoid data loss.

### ISSUE THREAD

**Issue by dferreras439** [Ariescyn/EldenRing-Save-Manager#42]
"On clicking "Load Save", prompt to save current game file to avoid data loss."

So before the save file gets replaced, user can save it in one of the files.

**Comment by Ariescyn** [comment]
Hey there, I can do this.
However the save manager already automatically backs up the save file before you overwrite it to prevent data loss. You can find it in file recovery, just look for the entry that starts with "None"
