### ISSUE TITLE
Please maybe change some code or apis becasue this file appears as malicious to virus scanners

### ISSUE THREAD

**Issue by ZezakTeQelbur** [Ariescyn/EldenRing-Save-Manager#44]

**Comment by Ariescyn** [comment]
That's because I compiled it to an executable with pyinstaller. I already have contacted Microsoft defender and AVG and they have removed the false positive from their software

**Comment by ZezakTeQelbur** [comment]
and i really dont wanna bother u but if u maybe have a time frame of when the save manager can add items to your inventory that arnt already in there

**Comment by Ariescyn** [comment]
Sorry i misunderstood you. If you don't have an item in your inventory and you want to add it, use the item replacer tool and then you can set quantity

**Comment by ZezakTeQelbur** [comment]
> 

huh well i tried it and also saved and loaded the save but it doesnt work so i thought it was to give items between saves like from other saves
