### ISSUE TITLE
Request: Is it possible to recover a deleted character?

### ISSUE THREAD

**Issue by marcosking** [Ariescyn/EldenRing-Save-Manager#46]
Hi,

I know the saves still store deleted characters. My son accidently deleted one.  Is it possible to restore a deleted character?

**Comment by Ariescyn** [comment]
If you were using the save manager before he deleted the character then you can revert to an earlier save using the file recovery tool. 

I'm not sure how to recover a deleted character since I don't know how/where the flag is written that signifies it was deleted. I will look into this and do some testing and let you know if I figured it out

**Comment by Ariescyn** [comment]
If you can try to find a backup of the save file right after the character was deleted that would be best. Also if you made a new character then it will overwrite the deleted character so hopefully you haven't done that yet

**Comment by Ariescyn** [comment]
I was able to recover the characters using the manager and sent your save file back to you.

For others that have the same issue:

You will need 2 identical copies of your save file loaded into the manager.

Load up save file (A) and create a new character, this will overwrite the deleted character and mark the slot as not deleted.

Now right-click on save file (A) in the manager and click update. This will update the copy stored in the manager with the currently loaded save.

Go to character manager, select save (B) as the source and save (A) as the destination.

Copy your deleted character that you want recovered to save (A), overwriting the character you just created in the earlier step.

I will post a video for anyone else that might be looking to recover a deleted character.
