### ISSUE TITLE
Request: Change character location

### ISSUE THREAD

**Issue by Ran-Mewo** [Ariescyn/EldenRing-Save-Manager#48]
So I recently somehow glitched my main save file from seamless coop, I was playing with my friends and they unlocked the round table while I was away, after the coop ended I saw that I haven't unlocked it and so I tried to unlock it and upon being teleported to the round table I got stuck into an infinite loading screen

The game loads into the game for like 0.1 second then gets into another loading screen and keeps doing this forever

Changing my character location should fix it I hope
(I have lots of stuff in it! I don't wanna lose my save)

## Update:
I managed to fix it by changing my location using another tool known as Elden Ring Debug Tool. I'll keep this issue open as it'll be nice to have location editor in this tool too!

**Comment by Ariescyn** [comment]
Cool thanks, i just posted on his GitHub, hopefully he can provide some insight so i can add this functionality to the save manager

**Comment by SrBreus** [comment]
Hi, i have the same problem, literally. I already install the "Elden Ring Debug Tool" and i´m triying to fix the issue but i can´t.

I don´t know if im doing something wrong or what's happening. I hope you can help me or guide me to use the tool to fix the issue to still playing with my friends. TY so much

**Comment by javiermojito** [comment]
Hey @Ran-Mewo, I friend of mine is facing the same issue. How did you solve it? Could you help us?
