### ISSUE TITLE
Requesting New option

### ISSUE THREAD

**Issue by Drakengard2099** [Ariescyn/EldenRing-Save-Manager#5]
I couldn't find anywhere to send this to you. I was hoping to find a means to edit my inventory, primarily to remove any item from my inventory.  Any help would be greatly appreciated

**Comment by Ariescyn** [comment]
Why would you want to remove items from your inventory? Ive played around with items a bit and can add items like larval tears or certain runes. I might release it in a future update

**Comment by Drakengard2099** [comment]
> Why would you want to remove items from your inventory? Ive played around with items a bit and can add items like larval tears or certain runes. I might release it in a future update

Because I picked up an item, and apparently I cant just drop them or leave them. So if its possible, any help would be greatly appreciated

**Comment by Ariescyn** [comment]
I added the lords rune, rune arcs, and standard smithing stones. It'll be available in the next update. Let me know if there are other items you want
