### ISSUE TITLE
Can't remove custom items

### ISSUE THREAD

**Issue by UnholyScribe** [Ariescyn/EldenRing-Save-Manager#51]
![image_2023-11-29_201423863](https://github.com/Ariescyn/EldenRing-Save-Manager/assets/55654759/8ad22f44-7d49-487a-b504-e0f19a997a1f)

**Comment by Ariescyn** [comment]
Thanks for the report ill look into it.
If you want to get rid of that item just open the config.json in the data folder and take out the items you want
