### ISSUE TITLE
010 template / info about SL2 format?

### ISSUE THREAD

**Issue by ividyon** [Ariescyn/EldenRing-Save-Manager#52]
It seems like you've done a lot of reverse engineering work for this project. Is any of your raw work available? It would be nice to have SL2 figured out as a template for the 010 hex editor, or as a SoulsFormats C# class...

**Comment by Ariescyn** [comment]
Sorry most of my reverse engineering efforts involved me rapidly writing and rewriting sloppy python functions to compare different save files and poop out numbers on the terminal or to a text file for analysis. I didn't have any real system and i didn't use any tools, which would probably have helped me tremendously.

The best advice i can give you is look at the hexedit.py script and there are many static addresses and marked sections of data that may be of help. 

The biggest challenge is that even when you just load into a save and immediately exit, massive amounts of data shifts around. I couldn't figure out a predictable offset or pattern to where segments of data move to. So some of my functions just look for patterns and they won't be of any use to you.
