### ISSUE TITLE
Not All Crafting Materials Are Listed

### ISSUE THREAD

**Issue by dungeon-mystic** [Ariescyn/EldenRing-Save-Manager#54]
Most crafting materials do not appear on the list. Only arteria leaf, flight pinion, gold fireflies, root resin, old fang, dragonfly head, and golden centipede do. Can the rest of the crafting materials be added?

**Comment by Ariescyn** [comment]
Yes the full list of items can be found here

https://github.com/Ariescyn/EldenRing-Save-Manager/blob/main/ALL_ITEM_IDS.md

In the save manager inventory editor window click actions > add item by ID

**Comment by Ariescyn** [comment]
It will appear in custom items from the dropdown.

This is a bit outdated but should help

https://youtu.be/li-ZiMXBmRk?si=cr9onONTGFb_juEV

**Comment by dungeon-mystic** [comment]
Thank you, the items are there
