### ISSUE TITLE
Release 1.44 regression

### ISSUE THREAD

**Issue by chozandrias76** [Ariescyn/EldenRing-Save-Manager#7]
## Expected
As a user
I expect to be able load a save
And for my application to send me a success alert

## Actual
![image](https://user-images.githubusercontent.com/2087677/165647387-288f796d-cf59-4eab-aad7-9ace6d1dd023.png)

Source of the issue:
https://github.com/Ariescyn/EldenRing-Save-Manager/pull/6
https://github.com/Ariescyn/EldenRing-Save-Manager/commit/ffca9f19cf83e73b25ea9b43ac2571a555a45448#diff-81a3bf39dea415dc9adb50169b89e01182495922e6e1567b034253bc6f9e4a4dR284

**Comment by VinegarLove** [comment]
To solve the problem, you can delete the data/GameSaveDir.txt
Before deleting, could you give me the full string inside so i can do a check to convert 1.43 to 1.44 format in code? Thanks

**Comment by chozandrias76** [comment]
Thanks, looks like you resolved the issue!
