### ISSUE TITLE
Images identified in SaveManager.py are not checked into the project

### ISSUE THREAD

**Issue by chozandrias76** [Ariescyn/EldenRing-Save-Manager#9]
Is there something I'm missing? I don't see 
./data/assets/but_done.png
./data/assets/but_load_save.png
./data/assets/but_delete_save.png
or any assets directory
https://github.com/Ariescyn/EldenRing-Save-Manager/blob/783b9419a9d75f8f3af3c9b2ea25b5b63fbd6e71/SaveManager.py#L1356

**Comment by Ariescyn** [comment]
Sorry i forgot to add them to the repo, done now
